---
version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 81:80    
  go:
     build: .
     restart: on-failure
     depends_on:
        - db
     ports:
       - 8000:8000      
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: asdf
      MYSQL_PASSWORD: asdfasdf
      MYSQL_ROOT_PASSWORD: sensei
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql   
volumes:
  my-db: null
  
